#ifndef TESTCOINSUPER_CHAINPARAMSSEEDS_H
#define TESTCOINSUPER_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the testcoinsuper network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside an IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,127,0,0,1}, 7563}
};

static SeedSpec6 pnSeed6_test[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,127,0,0,1}, 17563}
};
#endif // TESTCOINSUPER_CHAINPARAMSSEEDS_H
